apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: stakater-control-sealed-secrets
  namespace: control
spec:
  releaseName: stakater-control-sealed-secrets
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: sealed-secrets
    version: 1.0.2
  values:
    serviceAccount:
      # serviceAccount.create: Whether to create a service account or not
      create: true
      # serviceAccount.name: The name of the service account to create or use
      name: ""

    rbac:
      # rbac.create: `true` if rbac resources should be created
      create: true

    # secretName: The name of the TLS secret containing the key used to encrypt secrets
    secretName: "sealed-secrets-key"

    crd:
      # crd.create: `true` if the crd resources should be created
      create: false
      # crd.keep: `true` if the sealed secret CRD should be kept when the chart is deleted
      keep: true